---
title: "Sports Analytics Project"
author: "Joseph Marino"
date: "10/19/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse) # Load tidyverse
library(ggplot2) # Load ggplot2
library(ggdark) # Load ggdark
library(ggimage) # Load ggimage
library(GGally) # Load GGally
library(ggrepel) # Load ggrepel
library(ggalt) # Used for dumbbell plot
```


```{r}
pitcher_data <- read.csv("Pitchers_past_5_years.csv")
pitchers_2016_19 <- pitcher_data[pitcher_data$year <= 2019,]
pitchers_2020 <- pitcher_data[pitcher_data$year == 2020,]
pitchers_2019 <- pitcher_data[pitcher_data$year == 2019,]
pitchers_2018 <- pitcher_data[pitcher_data$year == 2018,]
pitchers_2017 <- pitcher_data[pitcher_data$year == 2017,]
pitchers_2016 <- pitcher_data[pitcher_data$year == 2016,]

head(pitcher_data)
summary(pitcher_data)
```

```{r}
# Preliminary Analysis

fit_1 <- lm(p_win ~ exit_velocity_avg + launch_angle_avg + (z_swing_miss_percent + oz_swing_miss_percent) + (pitch_count_offspeed + pitch_count_fastball + pitch_count_breaking) + edge_percent,
            data = pitchers_2016_19)
summary(fit_1)
```

```{r}
# 2016-2019 Visualizations

g_1 <- ggplot(pitchers_2016_19, # Set dataset
              aes(x = p_win,  # Set number of wins
                  y = pitch_count_fastball,  # Set pitch count of fastballs
                  color = year)) + # Set color as year
  geom_point(alpha = 0.7) + # Set geom_point for scatter
  geom_smooth(inherit.aes = FALSE, aes(x = p_win, y = pitch_count_fastball)) + # Show regression line
  dark_theme_bw() + # Set theme as dark mode
   theme(legend.position = "right", # Turn off legend
     panel.grid.major = element_blank(), # Remove grid
        panel.grid.minor = element_blank(), # Remove grid
        panel.border = element_blank(), # Remove grid
        panel.background = element_blank()) +  # Remove grid
    labs(y= "Fastballs Thrown", x ="Wins", # Set labels
       title = "Win to Fastballs Correlation",
       subtitle = "MLB Pitchers 2016-2019")
g_1

g_2 <- ggplot(pitchers_2016_19, # Set dataset
              aes(x = p_win,  # Set number of wins
                  y = pitch_count_breaking,  # Set pitch count of breaking balls
                  color = year)) + # Set color as year
  geom_point(alpha = 0.7) + # Set geom_point for scatter
  geom_smooth(inherit.aes = FALSE, aes(x = p_win, y = pitch_count_breaking)) + # Show regression line
  dark_theme_bw() + # Set theme as dark mode
   theme(legend.position = "right", # Turn off legend
     panel.grid.major = element_blank(), # Remove grid
        panel.grid.minor = element_blank(), # Remove grid
        panel.border = element_blank(), # Remove grid
        panel.background = element_blank()) +  # Remove grid
    labs(y= "Breaking Balls Thrown", x ="Wins", # Set labels
       title = "Win to Breaking Balls Correlation",
       subtitle = "MLB Pitchers 2016-2019")
g_2
```

```{r}
fit_2 <- lm(p_win ~ (fastball_avg_speed + fastball_avg_spin + fastball_avg_break_x) + (sl_avg_speed + sl_avg_spin + sl_avg_break) + whiff_percent,
            data = pitchers_2016_19)
summary(fit_2)
```

```{r}
# More 2016-2019 Visualizations

g_3 <- ggplot(pitchers_2016_19, # Set dataset
              aes(x = p_win,  # Set number of wins
                  y = sl_avg_speed,  # Set slider avg speed
                  color = year)) + # Set color as year
  geom_point(alpha = 0.7) + # Set geom_point for scatter
  geom_smooth(inherit.aes = FALSE, aes(x = p_win, y = sl_avg_speed)) + # Show regression line
  dark_theme_bw() + # Set theme as dark mode
   theme(legend.position = "right", # Turn off legend
     panel.grid.major = element_blank(), # Remove grid
        panel.grid.minor = element_blank(), # Remove grid
        panel.border = element_blank(), # Remove grid
        panel.background = element_blank()) +  # Remove grid
    labs(y= "Avg Slider Speed", x ="Wins", # Set labels
       title = "Win to Slider Speed Correlation",
       subtitle = "MLB Pitchers 2016-2019")
g_3

g_4 <- ggplot(pitchers_2016_19, # Set dataset
              aes(x = p_win,  # Set number of wins
                  y = fastball_avg_spin,  # Set fastball avg spin
                  color = year)) + # Set color as year
  geom_point(alpha = 0.7) + # Set geom_point for scatter
  geom_smooth(inherit.aes = FALSE, aes(x = p_win, y = fastball_avg_spin)) + # Show regression line
  dark_theme_bw() + # Set theme as dark mode
   theme(legend.position = "right", # Turn off legend
     panel.grid.major = element_blank(), # Remove grid
        panel.grid.minor = element_blank(), # Remove grid
        panel.border = element_blank(), # Remove grid
        panel.background = element_blank()) +  # Remove grid
    labs(y= "Avg Fastball Spin (rpm)", x ="Wins", # Set labels
       title = "Win to Fastball Spin Correlation",
       subtitle = "MLB Pitchers 2016-2019")
g_4

g_5 <- ggplot(pitchers_2016_19, # Set dataset
              aes(x = p_win,  # Set number of wins
                  y = player_age,  # Set player age
                  color = year)) + # Set color as year
  geom_point(alpha = 0.7) + # Set geom_point for scatter
  geom_smooth(inherit.aes = FALSE, aes(x = p_win, y = player_age)) + # Show regression line
  dark_theme_bw() + # Set theme as dark mode
   theme(legend.position = "right", # Turn off legend
     panel.grid.major = element_blank(), # Remove grid
        panel.grid.minor = element_blank(), # Remove grid
        panel.border = element_blank(), # Remove grid
        panel.background = element_blank()) +  # Remove grid
    labs(y= "Age", x ="Wins", # Set labels
       title = "Win to Pitcher Age Correlation",
       subtitle = "MLB Pitchers 2016-2019")
g_5

g_6 <- ggplot(pitchers_2016_19, # Set dataset
              aes(x = player_age,  # Set palyer age
                  y = fastball_avg_spin,  # Set fastball avg spin
                  color = year)) + # Set color as year
  geom_point(alpha = 0.7) + # Set geom_point for scatter
  geom_smooth(inherit.aes = FALSE, aes(x = player_age, y = fastball_avg_spin)) + # Show regression line
  dark_theme_bw() + # Set theme as dark mode
   theme(legend.position = "right", # Turn off legend
     panel.grid.major = element_blank(), # Remove grid
        panel.grid.minor = element_blank(), # Remove grid
        panel.border = element_blank(), # Remove grid
        panel.background = element_blank()) +  # Remove grid
    labs(y= "Avg Fastball Spin (rpm)", x ="Age", # Set labels
       title = "Pitcher Age to Fastball Spin Correlation",
       subtitle = "MLB Pitchers 2016-2019")
g_6
```
```{r}
# 2016, 17, 18, 19 Fastball Spin Visualizations

g_7 <- ggplot(pitchers_2016, # Set dataset
              aes(x = p_win,  # Set number of wins
                  y = fastball_avg_spin,  # Set fastball avg spin
                  color = year)) + # Set color as year
  geom_point(alpha = 0.7) + # Set geom_point for scatter
  geom_smooth(inherit.aes = FALSE, aes(x = p_win, y = fastball_avg_spin)) + # Show regression line
  dark_theme_bw() + # Set theme as dark mode
   theme(legend.position = "right", # Turn off legend
     panel.grid.major = element_blank(), # Remove grid
        panel.grid.minor = element_blank(), # Remove grid
        panel.border = element_blank(), # Remove grid
        panel.background = element_blank()) +  # Remove grid
    labs(y= "Avg Fastball Spin (rpm)", x ="Wins", # Set labels
       title = "Win to Fastball Spin Correlation",
       subtitle = "MLB Pitchers 2016")
g_7

g_8 <- ggplot(pitchers_2017, # Set dataset
              aes(x = p_win,  # Set number of wins
                  y = fastball_avg_spin,  # Set fastball avg spin
                  color = year)) + # Set color as year
  geom_point(alpha = 0.7) + # Set geom_point for scatter
  geom_smooth(inherit.aes = FALSE, aes(x = p_win, y = fastball_avg_spin)) + # Show regression line
  dark_theme_bw() + # Set theme as dark mode
   theme(legend.position = "right", # Turn off legend
     panel.grid.major = element_blank(), # Remove grid
        panel.grid.minor = element_blank(), # Remove grid
        panel.border = element_blank(), # Remove grid
        panel.background = element_blank()) +  # Remove grid
    labs(y= "Avg Fastball Spin (rpm)", x ="Wins", # Set labels
       title = "Win to Fastball Spin Correlation",
       subtitle = "MLB Pitchers 2017")
g_8

g_9 <- ggplot(pitchers_2018, # Set dataset
              aes(x = p_win,  # Set number of wins
                  y = fastball_avg_spin,  # Set fastball avg spin
                  color = year)) + # Set color as year
  geom_point(alpha = 0.7) + # Set geom_point for scatter
  geom_smooth(inherit.aes = FALSE, aes(x = p_win, y = fastball_avg_spin)) + # Show regression line
  dark_theme_bw() + # Set theme as dark mode
   theme(legend.position = "right", # Turn off legend
     panel.grid.major = element_blank(), # Remove grid
        panel.grid.minor = element_blank(), # Remove grid
        panel.border = element_blank(), # Remove grid
        panel.background = element_blank()) +  # Remove grid
    labs(y= "Avg Fastball Spin (rpm)", x ="Wins", # Set labels
       title = "Win to Fastball Spin Correlation",
       subtitle = "MLB Pitchers 2018")
g_9

g_10 <- ggplot(pitchers_2019, # Set dataset
              aes(x = p_win,  # Set number of wins
                  y = fastball_avg_spin,  # Set fastball avg spin
                  color = year)) + # Set color as year
  geom_point(alpha = 0.7) + # Set geom_point for scatter
  geom_smooth(inherit.aes = FALSE, aes(x = p_win, y = fastball_avg_spin)) + # Show regression line
  dark_theme_bw() + # Set theme as dark mode
   theme(legend.position = "right", # Turn off legend
     panel.grid.major = element_blank(), # Remove grid
        panel.grid.minor = element_blank(), # Remove grid
        panel.border = element_blank(), # Remove grid
        panel.background = element_blank()) +  # Remove grid
    labs(y= "Avg Fastball Spin (rpm)", x ="Wins", # Set labels
       title = "Wins to Fastball Spin Correlation",
       subtitle = "MLB Pitchers 2019")
g_10

```


```{r}
fit_3 <- lm(p_win ~ exit_velocity_avg + launch_angle_avg + (z_swing_miss_percent + oz_swing_miss_percent) + (pitch_count_offspeed + pitch_count_fastball + pitch_count_breaking) + edge_percent,
            data = pitchers_2020)
summary(fit_3)
```

```{r}
# 2020 Visualizations

g_11 <- ggplot(pitchers_2020, # Set dataset
              aes(x = p_win,  # Set number of wins
                  y = pitch_count_fastball,  # Set pitch count of fastballs
                  color = year)) + # Set color as year
  geom_point(alpha = 0.7) + # Set geom_point for scatter
  geom_smooth(inherit.aes = FALSE, aes(x = p_win, y = pitch_count_fastball)) + # Show regression line
  dark_theme_bw() + # Set theme as dark mode
   theme(legend.position = "none", # Turn off legend
     panel.grid.major = element_blank(), # Remove grid
        panel.grid.minor = element_blank(), # Remove grid
        panel.border = element_blank(), # Remove grid
        panel.background = element_blank()) +  # Remove grid
    labs(y= "Fastballs Thrown", x ="Wins", # Set labels
       title = "Win to Fastballs Correlation",
       subtitle = "MLB Pitchers 2020")
g_11

g_12 <- ggplot(pitchers_2020, # Set dataset
              aes(x = p_win,  # Set number of wins
                  y = pitch_count_breaking,  # Set pitch count of breaking balls
                  color = year)) + # Set color as year
  geom_point(alpha = 0.7) + # Set geom_point for scatter
  geom_smooth(inherit.aes = FALSE, aes(x = p_win, y = pitch_count_breaking)) + # Show regression line
  dark_theme_bw() + # Set theme as dark mode
   theme(legend.position = "none", # Turn off legend
     panel.grid.major = element_blank(), # Remove grid
        panel.grid.minor = element_blank(), # Remove grid
        panel.border = element_blank(), # Remove grid
        panel.background = element_blank()) +  # Remove grid
    labs(y= "Breaking Balls Thrown", x ="Wins", # Set labels
       title = "Win to Breaking Balls Correlation",
       subtitle = "MLB Pitchers 2020")
g_12
```

```{r}
fit_4 <- lm(p_win ~ (fastball_avg_speed + fastball_avg_spin + fastball_avg_break_x) + (sl_avg_speed + sl_avg_spin + sl_avg_break) + whiff_percent,
            data = pitchers_2020)
summary(fit_4)
```

```{r}
# More 2020 Visualizations

g_13 <- ggplot(pitchers_2020, # Set dataset
              aes(x = p_win,  # Set number of wins
                  y = sl_avg_speed,  # Set slider avg speed
                  color = year)) + # Set color as year
  geom_point(alpha = 0.7) + # Set geom_point for scatter
  geom_smooth(inherit.aes = FALSE, aes(x = p_win, y = sl_avg_speed)) + # Show regression line
  dark_theme_bw() + # Set theme as dark mode
   theme(legend.position = "right", # Turn off legend
     panel.grid.major = element_blank(), # Remove grid
        panel.grid.minor = element_blank(), # Remove grid
        panel.border = element_blank(), # Remove grid
        panel.background = element_blank()) +  # Remove grid
    labs(y= "Avg Slider Speed", x ="Wins", # Set labels
       title = "Win to Slider Speed Correlation",
       subtitle = "MLB Pitchers 2020")
g_13

g_14 <- ggplot(pitchers_2020, # Set dataset
              aes(x = p_win,  # Set number of wins
                  y = fastball_avg_spin,  # Set fastball avg spin
                  color = year)) + # Set color as year
  geom_point(alpha = 0.7) + # Set geom_point for scatter
  geom_smooth(inherit.aes = FALSE, aes(x = p_win, y = fastball_avg_spin)) + # Show regression line
  dark_theme_bw() + # Set theme as dark mode
   theme(legend.position = "right", # Turn off legend
     panel.grid.major = element_blank(), # Remove grid
        panel.grid.minor = element_blank(), # Remove grid
        panel.border = element_blank(), # Remove grid
        panel.background = element_blank()) +  # Remove grid
    labs(y= "Avg Fastball Spin (rpm)", x ="Wins", # Set labels
       title = "Win to Fastball Spin Correlation",
       subtitle = "MLB Pitchers 2020")
g_14

g_15 <- ggplot(pitchers_2020, # Set dataset
              aes(x = p_win,  # Set number of wins
                  y = whiff_percent,  # Set whiff percent
                  color = year)) + # Set color as year
  geom_point(alpha = 0.7) + # Set geom_point for scatter
  geom_smooth(inherit.aes = FALSE, aes(x = p_win, y = whiff_percent)) + # Show regression line
  dark_theme_bw() + # Set theme as dark mode
   theme(legend.position = "right", # Turn off legend
     panel.grid.major = element_blank(), # Remove grid
        panel.grid.minor = element_blank(), # Remove grid
        panel.border = element_blank(), # Remove grid
        panel.background = element_blank()) +  # Remove grid
    labs(y= "Whiff Percent", x ="Wins", # Set labels
       title = "Win to Whiff Percent Correlation",
       subtitle = "MLB Pitchers 2020")
g_15
```

```{r}
fit_5 <- lm(p_win ~ xwoba + sweet_spot_percent + solidcontact_percent + poorlyweak_percent,
            data = pitchers_2016_19)
summary(fit_5)

fit_6 <- lm(p_win ~ xwoba + sweet_spot_percent + solidcontact_percent + poorlyweak_percent,
            data = pitchers_2016)
summary(fit_6)

fit_7 <- lm(p_win ~ xwoba + sweet_spot_percent + solidcontact_percent + poorlyweak_percent,
            data = pitchers_2017)
summary(fit_7)

fit_8 <- lm(p_win ~ xwoba + sweet_spot_percent + solidcontact_percent + poorlyweak_percent,
            data = pitchers_2018)
summary(fit_8)

fit_9 <- lm(p_win ~ xwoba + sweet_spot_percent + solidcontact_percent + poorlyweak_percent,
            data = pitchers_2019)
summary(fit_9)
```

```{r}
# wxOBA Visualizations

g_16 <- ggplot(pitchers_2016_19, # Set dataset
              aes(x = p_win,  # Set number of wins
                  y = xwoba,  # Set xwOBA
                  color = year)) + # Set color as year
  geom_point(alpha = 0.7) + # Set geom_point for scatter
  geom_smooth(inherit.aes = FALSE, aes(x = p_win, y = xwoba)) + # Show regression line
  dark_theme_bw() + # Set theme as dark mode
   theme(legend.position = "right", # Turn off legend
     panel.grid.major = element_blank(), # Remove grid
        panel.grid.minor = element_blank(), # Remove grid
        panel.border = element_blank(), # Remove grid
        panel.background = element_blank()) +  # Remove grid
    labs(y= "xwOBA", x ="Wins", # Set labels
       title = "Win to xwOBA Correlation",
       subtitle = "MLB Pitchers 2016-2019")
g_16

g_17 <- ggplot(pitchers_2016, # Set dataset
              aes(x = p_win,  # Set number of wins
                  y = xwoba,  # Set xwOBA
                  color = year)) + # Set color as year
  geom_point(alpha = 0.7) + # Set geom_point for scatter
  geom_smooth(inherit.aes = FALSE, aes(x = p_win, y = xwoba)) + # Show regression line
  dark_theme_bw() + # Set theme as dark mode
   theme(legend.position = "right", # Turn off legend
     panel.grid.major = element_blank(), # Remove grid
        panel.grid.minor = element_blank(), # Remove grid
        panel.border = element_blank(), # Remove grid
        panel.background = element_blank()) +  # Remove grid
    labs(y= "xwOBA", x ="Wins", # Set labels
       title = "Win to xwOBA Correlation",
       subtitle = "MLB Pitchers 2016")
g_17

g_18 <- ggplot(pitchers_2017, # Set dataset
              aes(x = p_win,  # Set number of wins
                  y = xwoba,  # Set xwOBA
                  color = year)) + # Set color as year
  geom_point(alpha = 0.7) + # Set geom_point for scatter
  geom_smooth(inherit.aes = FALSE, aes(x = p_win, y = xwoba)) + # Show regression line
  dark_theme_bw() + # Set theme as dark mode
   theme(legend.position = "right", # Turn off legend
     panel.grid.major = element_blank(), # Remove grid
        panel.grid.minor = element_blank(), # Remove grid
        panel.border = element_blank(), # Remove grid
        panel.background = element_blank()) +  # Remove grid
    labs(y= "xwOBA", x ="Wins", # Set labels
       title = "Win to xwOBA Correlation",
       subtitle = "MLB Pitchers 2017")
g_18

g_19 <- ggplot(pitchers_2018, # Set dataset
              aes(x = p_win,  # Set number of wins
                  y = xwoba,  # Set xwOBA
                  color = year)) + # Set color as year
  geom_point(alpha = 0.7) + # Set geom_point for scatter
  geom_smooth(inherit.aes = FALSE, aes(x = p_win, y = xwoba)) + # Show regression line
  dark_theme_bw() + # Set theme as dark mode
   theme(legend.position = "right", # Turn off legend
     panel.grid.major = element_blank(), # Remove grid
        panel.grid.minor = element_blank(), # Remove grid
        panel.border = element_blank(), # Remove grid
        panel.background = element_blank()) +  # Remove grid
    labs(y= "xwOBA", x ="Wins", # Set labels
       title = "Win to xwOBA Correlation",
       subtitle = "MLB Pitchers 2018")
g_19

g_20 <- ggplot(pitchers_2019, # Set dataset
              aes(x = p_win,  # Set number of wins
                  y = xwoba,  # Set xwOBA
                  color = year)) + # Set color as year
  geom_point(alpha = 0.7) + # Set geom_point for scatter
  geom_smooth(inherit.aes = FALSE, aes(x = p_win, y = xwoba)) + # Show regression line
  dark_theme_bw() + # Set theme as dark mode
   theme(legend.position = "right", # Turn off legend
     panel.grid.major = element_blank(), # Remove grid
        panel.grid.minor = element_blank(), # Remove grid
        panel.border = element_blank(), # Remove grid
        panel.background = element_blank()) +  # Remove grid
    labs(y= "xwOBA", x ="Wins", # Set labels
       title = "Win to xwOBA Correlation",
       subtitle = "MLB Pitchers 2019")
g_20

g_21 <- ggplot(pitchers_2020, # Set dataset
              aes(x = p_win,  # Set number of wins
                  y = xwoba,  # Set xwOBA
                  color = year)) + # Set color as year
  geom_point(alpha = 0.7) + # Set geom_point for scatter
  geom_smooth(inherit.aes = FALSE, aes(x = p_win, y = xwoba)) + # Show regression line
  dark_theme_bw() + # Set theme as dark mode
   theme(legend.position = "right", # Turn off legend
     panel.grid.major = element_blank(), # Remove grid
        panel.grid.minor = element_blank(), # Remove grid
        panel.border = element_blank(), # Remove grid
        panel.background = element_blank()) +  # Remove grid
    labs(y= "xwOBA", x ="Wins", # Set labels
       title = "Win to xwOBA Correlation",
       subtitle = "MLB Pitchers 2020")
g_21

```

# Hierarchical Clustering

```{r}
library(cluster)
library(factoextra)
library(dendextend)
library(circlize)
```

```{r}
# Data cleaning for clustering

# Create vector of variables to be dropped
drop_vars <- c("n_kn_formatted","kn_avg_speed","kn_avg_spin","kn_avg_break_x",
               "kn_avg_break_z","kn_avg_break", "kn_range_speed")

# Create dataframe with updated columns
df_pitchers <- as.data.frame(pitcher_data)
updated_pitchers <- df_pitchers[, !(colnames(df_pitchers) %in% drop_vars)]
str(updated_pitchers)
updated_pitchers$pitch_hand <- as.numeric(as.factor(updated_pitchers$pitch_hand)) - 1

# Scale data 
scale_pitchers <- scale(updated_pitchers[, 3:ncol(updated_pitchers)])
scale_pitchers[is.na(scale_pitchers)] <- 0

# Add teams back to data frame
scale_pitchers <- cbind.data.frame(updated_pitchers$first_name, 
                                   updated_pitchers$last_name, 
                                   scale_pitchers)
# Fix name of team column
names(scale_pitchers)[1] <- "first_name"
names(scale_pitchers)[2] <- "last_name"

# Make datasets by year
scale_pitchers_2016_19 <- scale_pitchers[updated_pitchers$year <= 2019,]
scale_pitchers_2020 <- scale_pitchers[updated_pitchers$year == 2020,]
scale_pitchers_2019 <- scale_pitchers[updated_pitchers$year == 2019,]
scale_pitchers_2018 <- scale_pitchers[updated_pitchers$year == 2018,]
scale_pitchers_2017 <- scale_pitchers[updated_pitchers$year == 2017,]
scale_pitchers_2016 <- scale_pitchers[updated_pitchers$year == 2016,]

# Assign first and last names to each dataset
rownames(scale_pitchers) <- paste(updated_pitchers$first_name, 
                                  updated_pitchers$last_name, updated_pitchers$year)
rownames(scale_pitchers_2016) <- paste(updated_pitchers$first_name[updated_pitchers$year == 2016],
                                       updated_pitchers$last_name[updated_pitchers$year == 2016])
rownames(scale_pitchers_2017) <- paste(updated_pitchers$first_name[updated_pitchers$year == 2017],
                                       updated_pitchers$last_name[updated_pitchers$year == 2017])
rownames(scale_pitchers_2018) <- paste(updated_pitchers$first_name[updated_pitchers$year == 2018],
                                       updated_pitchers$last_name[updated_pitchers$year == 2018])
rownames(scale_pitchers_2019) <- paste(updated_pitchers$first_name[updated_pitchers$year == 2019],
                                       updated_pitchers$last_name[updated_pitchers$year == 2019])
rownames(scale_pitchers_2020) <- paste(updated_pitchers$first_name[updated_pitchers$year == 2020],
                                       updated_pitchers$last_name[updated_pitchers$year == 2020])

#head(scale_pitchers)
#summary(scale_pitchers)
```

```{r}
# 2016 Hierarchical Clustering
# Calculate distances between points
dist_pitchers <- dist(scale_pitchers_2016, method = "euclidean")

# Run hierarchical clustering
hc <- hclust(dist_pitchers, method = "average" ) 

plot(hc, # Set hierarchical clustering as plot object
     cex = 0.6, # Set text size
     hang = -1 ) # Set label position

# Show potential clusters in dendrogram
plot(hc, # Set hierarchical clustering as plot object
     cex = 0.6,  # Set text size
     hang = -1) # Set label position

# Draw rectangles around branches/clusters
rect.hclust(hc, # Set hierarchical clustering object
            k = 5, # Set number of clusters 
            border = 2:6) # Sets colors for rectangles
```

```{r}
# Nicer Dendrogram
dend <- as.dendrogram(hc)
# order it the closest we can to the order of the observations:
dend <- rotate(dend, 1:50)

# Color the branches based on the clusters:
dend <- color_branches(dend, k=5) 

# We hang the dendrogram a bit:
dend <- hang.dendrogram(dend,hang_height=0.1)
# reduce the size of the labels:
dend <- set(dend, "labels_cex", 0.55)
# And plot:
par(mar = c(3,3,3,7))
plot(dend, 
     main = "2016 Clustered Pitchers Data",
     horiz =  TRUE,  nodePar = list(cex = .007))
jpeg(width = 12, height = 12, units = "in", filename = "2016_clustering_plot.jpeg", res = 600)
plot(dend, 
     main = "2016 Clustered Pitchers Data",
     horiz =  TRUE,  nodePar = list(cex = .007))
dev.off()

# Circular Dendrogram
par(mar = rep(0,4))
circlize_dendrogram(dend)
```

```{r}
clusters <- cutree(hc, # Specify object
                   k = 5) # Specify number of clusters

fviz_cluster(list(data = scale_pitchers_2016[, 4:nrow(scale_pitchers_2016)], cluster = clusters)) # Set clusters
```

```{r}
# 2017 Hierarchical Clustering
# Calculate distances between points
dist_pitchers <- dist(scale_pitchers_2017, method = "euclidean")

# Run hierarchical clustering
hc <- hclust(dist_pitchers, method = "average" ) 

plot(hc, # Set hierarchical clustering as plot object
     cex = 0.6, # Set text size
     hang = -1 ) # Set label position

# Show potential clusters in dendrogram
plot(hc, # Set hierarchical clustering as plot object
     cex = 0.6,  # Set text size
     hang = -1) # Set label position

# Draw rectangles around branches/clusters
rect.hclust(hc, # Set hierarchical clustering object
            k = 5, # Set number of clusters 
            border = 2:6) # Sets colors for rectangles

# Nicer Dendrogram
dend <- as.dendrogram(hc)
# order it the closest we can to the order of the observations:
dend <- rotate(dend, 1:50)

# Color the branches based on the clusters:
dend <- color_branches(dend, k=5) 

# We hang the dendrogram a bit:
dend <- hang.dendrogram(dend,hang_height=0.1)
# reduce the size of the labels:
dend <- set(dend, "labels_cex", 0.55)
# And plot:
par(mar = c(3,3,3,7))
plot(dend, 
     main = "2017 Clustered Pitchers Data",
     horiz =  TRUE,  nodePar = list(cex = .007))
jpeg(width = 12, height = 12, units = "in", filename = "2017_clustering_plot.jpeg", res = 600)
plot(dend, 
     main = "2017 Clustered Pitchers Data",
     horiz =  TRUE,  nodePar = list(cex = .007))
dev.off()

# Circular Dendrogram
par(mar = rep(0,4))
circlize_dendrogram(dend)

clusters <- cutree(hc, # Specify object
                   k = 5) # Specify number of clusters

fviz_cluster(list(data = scale_pitchers_2017[, 4:nrow(scale_pitchers_2017)], cluster = clusters)) # Set clusters
```

```{r}
# 2018 Hierarchical Clustering
# Calculate distances between points
dist_pitchers <- dist(scale_pitchers_2018, method = "euclidean")

# Run hierarchical clustering
hc <- hclust(dist_pitchers, method = "average" ) 

plot(hc, # Set hierarchical clustering as plot object
     cex = 0.6, # Set text size
     hang = -1 ) # Set label position

# Show potential clusters in dendrogram
plot(hc, # Set hierarchical clustering as plot object
     cex = 0.6,  # Set text size
     hang = -1) # Set label position

# Draw rectangles around branches/clusters
rect.hclust(hc, # Set hierarchical clustering object
            k = 5, # Set number of clusters 
            border = 2:6) # Sets colors for rectangles

# Nicer Dendrogram
dend <- as.dendrogram(hc)
# order it the closest we can to the order of the observations:
dend <- rotate(dend, 1:50)

# Color the branches based on the clusters:
dend <- color_branches(dend, k=5) 

# We hang the dendrogram a bit:
dend <- hang.dendrogram(dend,hang_height=0.1)
# reduce the size of the labels:
dend <- set(dend, "labels_cex", 0.55)
# And plot:
par(mar = c(3,3,3,7))
plot(dend, 
     main = "2018 Clustered Pitchers Data",
     horiz =  TRUE,  nodePar = list(cex = .007))
jpeg(width = 12, height = 12, units = "in", filename = "2018_clustering_plot.jpeg", res = 600)
plot(dend, 
     main = "2018 Clustered Pitchers Data",
     horiz =  TRUE,  nodePar = list(cex = .007))
dev.off()

# Circular Dendrogram
par(mar = rep(0,4))
circlize_dendrogram(dend)

clusters <- cutree(hc, # Specify object
                   k = 5) # Specify number of clusters

fviz_cluster(list(data = scale_pitchers_2018[, 4:nrow(scale_pitchers_2018)], cluster = clusters)) # Set clusters
```

```{r}
# 2019 Hierarchical Clustering
# Calculate distances between points
dist_pitchers <- dist(scale_pitchers_2019, method = "euclidean")

# Run hierarchical clustering
hc <- hclust(dist_pitchers, method = "average" ) 

plot(hc, # Set hierarchical clustering as plot object
     cex = 0.6, # Set text size
     hang = -1 ) # Set label position

# Show potential clusters in dendrogram
plot(hc, # Set hierarchical clustering as plot object
     cex = 0.6,  # Set text size
     hang = -1) # Set label position

# Draw rectangles around branches/clusters
rect.hclust(hc, # Set hierarchical clustering object
            k = 5, # Set number of clusters 
            border = 2:6) # Sets colors for rectangles

# Nicer Dendrogram
dend <- as.dendrogram(hc)
# order it the closest we can to the order of the observations:
dend <- rotate(dend, 1:50)

# Color the branches based on the clusters:
dend <- color_branches(dend, k=5) 

# We hang the dendrogram a bit:
dend <- hang.dendrogram(dend,hang_height=0.1)
# reduce the size of the labels:
dend <- set(dend, "labels_cex", 0.55)
# And plot:
par(mar = c(3,3,3,7))
plot(dend, 
     main = "2019 Clustered Pitchers Data",
     horiz =  TRUE,  nodePar = list(cex = .007))
jpeg(width = 12, height = 12, units = "in", filename = "2019_clustering_plot.jpeg", res = 600)
plot(dend, 
     main = "2019 Clustered Pitchers Data",
     horiz =  TRUE,  nodePar = list(cex = .007))
dev.off()

# Circular Dendrogram
par(mar = rep(0,4))
circlize_dendrogram(dend)

clusters <- cutree(hc, # Specify object
                   k = 5) # Specify number of clusters

fviz_cluster(list(data = scale_pitchers_2019[, 4:nrow(scale_pitchers_2019)], cluster = clusters)) # Set clusters
```


```{r}
# 2020 Hierarchical Clustering
# Calculate distances between points
dist_pitchers <- dist(scale_pitchers_2020, method = "euclidean")

# Run hierarchical clustering
hc <- hclust(dist_pitchers, method = "average" ) 

plot(hc, # Set hierarchical clustering as plot object
     cex = 0.6, # Set text size
     hang = -1 ) # Set label position

# Show potential clusters in dendrogram
plot(hc, # Set hierarchical clustering as plot object
     cex = 0.6,  # Set text size
     hang = -1) # Set label position

# Draw rectangles around branches/clusters
rect.hclust(hc, # Set hierarchical clustering object
            k = 5, # Set number of clusters 
            border = 2:6) # Sets colors for rectangles

# Nicer Dendrogram
dend <- as.dendrogram(hc)
# order it the closest we can to the order of the observations:
dend <- rotate(dend, 1:40)

# Color the branches based on the clusters:
dend <- color_branches(dend, k=5) 

# We hang the dendrogram a bit:
dend <- hang.dendrogram(dend,hang_height=0.1)
# reduce the size of the labels:
dend <- set(dend, "labels_cex", 0.55)
# And plot:
par(mar = c(3,3,3,7))
plot(dend, 
     main = "2020 Clustered Pitchers Data",
     horiz =  TRUE,  nodePar = list(cex = .007))
jpeg(width = 12, height = 12, units = "in", filename = "2020_clustering_plot.jpeg", res = 600)
plot(dend, 
     main = "2020 Clustered Pitchers Data",
     horiz =  TRUE,  nodePar = list(cex = .007))
dev.off()

# Circular Dendrogram
par(mar = rep(0,4))
circlize_dendrogram(dend)

clusters <- cutree(hc, # Specify object
                   k = 5) # Specify number of clusters

fviz_cluster(list(data = scale_pitchers_2020[, 4:nrow(scale_pitchers_2020)], cluster = clusters)) # Set clusters
```

```{r}
# K Means Clustering 2016

set.seed(12345) # Set seed for reproducibility
fit_10 <- kmeans(x = scale_pitchers_2016[4:139], # Set data as explantory variables 
                centers = 4,  # Set number of clusters
                nstart = 25, # Set number of starts
                iter.max = 100 ) # Set maximum number of iterations to use

# Extract clusters
clusters_1 <- fit_10$cluster
# Extract centers
centers_1 <- fit_10$centers

summary(as.factor(clusters_1))

scale_pitchers_2016$last_name[clusters_1 == 1]
scale_pitchers_2016$last_name[clusters_1 == 2]
scale_pitchers_2016$last_name[clusters_1 == 3]
scale_pitchers_2016$last_name[clusters_1 == 4]

cluster <- c(1: 4)
center_df <- data.frame(cluster, centers_1)

# Reshape the data
center_reshape <- gather(center_df, features, values, player_age:offspeed_range_speed)
head(center_reshape)

g_heat_1 <- ggplot(data = center_reshape, aes(x = features, y = cluster, fill = values)) +
  scale_y_continuous(breaks = seq(1, 4, by = 1)) +
  geom_tile() +
  coord_equal() + 
  theme_set(theme_bw(base_size = 22) ) +
  scale_fill_gradient2(low = "blue", # Choose low color
                       mid = "white", # Choose mid color
                       high = "red", # Choose high color
                       midpoint =0, # Choose mid point
                       space = "Lab", 
                       na.value ="grey", # Choose NA value
                       guide = "colourbar", # Set color bar
                       aesthetics = "fill") + # Select aesthetics to apply
  coord_flip()
g_heat_1
```

```{r}
# K Means Clustering 2017

set.seed(12345) # Set seed for reproducibility
fit_11 <- kmeans(x = scale_pitchers_2017[4:139], # Set data as explantory variables 
                centers = 4,  # Set number of clusters
                nstart = 25, # Set number of starts
                iter.max = 100 ) # Set maximum number of iterations to use

# Extract clusters
clusters_1 <- fit_11$cluster
# Extract centers
centers_1 <- fit_11$centers

summary(as.factor(clusters_1))

scale_pitchers_2017$last_name[clusters_1 == 1]
scale_pitchers_2017$last_name[clusters_1 == 2]
scale_pitchers_2017$last_name[clusters_1 == 3] # look into this cluster
scale_pitchers_2017$last_name[clusters_1 == 4]

cluster <- c(1: 4)
center_df <- data.frame(cluster, centers_1)

# Reshape the data
center_reshape <- gather(center_df, features, values, player_age:offspeed_range_speed)
head(center_reshape)

g_heat_2 <- ggplot(data = center_reshape, aes(x = features, y = cluster, fill = values)) +
  scale_y_continuous(breaks = seq(1, 4, by = 1)) +
  geom_tile() +
  coord_equal() + 
  theme_set(theme_bw(base_size = 22) ) +
  scale_fill_gradient2(low = "blue", # Choose low color
                       mid = "white", # Choose mid color
                       high = "red", # Choose high color
                       midpoint =0, # Choose mid point
                       space = "Lab", 
                       na.value ="grey", # Choose NA value
                       guide = "colourbar", # Set color bar
                       aesthetics = "fill") + # Select aesthetics to apply
  coord_flip()
g_heat_2
```
```{r}
# K Means Clustering 2018

set.seed(12345) # Set seed for reproducibility
fit_12 <- kmeans(x = scale_pitchers_2018[4:139], # Set data as explantory variables 
                centers = 4,  # Set number of clusters
                nstart = 25, # Set number of starts
                iter.max = 100 ) # Set maximum number of iterations to use

# Extract clusters
clusters_1 <- fit_12$cluster
# Extract centers
centers_1 <- fit_12$centers

summary(as.factor(clusters_1))

scale_pitchers_2018$last_name[clusters_1 == 1]
scale_pitchers_2018$last_name[clusters_1 == 2]
scale_pitchers_2018$last_name[clusters_1 == 3] # look into this cluster
scale_pitchers_2018$last_name[clusters_1 == 4]

cluster <- c(1: 4)
center_df <- data.frame(cluster, centers_1)

# Reshape the data
center_reshape <- gather(center_df, features, values, player_age:offspeed_range_speed)
head(center_reshape)

g_heat_3 <- ggplot(data = center_reshape, aes(x = features, y = cluster, fill = values)) +
  scale_y_continuous(breaks = seq(1, 4, by = 1)) +
  geom_tile() +
  coord_equal() + 
  theme_set(theme_bw(base_size = 22) ) +
  scale_fill_gradient2(low = "blue", # Choose low color
                       mid = "white", # Choose mid color
                       high = "red", # Choose high color
                       midpoint =0, # Choose mid point
                       space = "Lab", 
                       na.value ="grey", # Choose NA value
                       guide = "colourbar", # Set color bar
                       aesthetics = "fill") + # Select aesthetics to apply
  coord_flip()
g_heat_3
```

```{r}
# K Means Clustering 2019

set.seed(12345) # Set seed for reproducibility
fit_13 <- kmeans(x = scale_pitchers_2019[4:139], # Set data as explantory variables 
                centers = 4,  # Set number of clusters
                nstart = 25, # Set number of starts
                iter.max = 100 ) # Set maximum number of iterations to use

# Extract clusters
clusters_1 <- fit_13$cluster
# Extract centers
centers_1 <- fit_13$centers

summary(as.factor(clusters_1))

scale_pitchers_2019$last_name[clusters_1 == 1]
scale_pitchers_2019$last_name[clusters_1 == 2] # look into this cluster
scale_pitchers_2019$last_name[clusters_1 == 3] # look into this cluster
scale_pitchers_2019$last_name[clusters_1 == 4]

cluster <- c(1: 4)
center_df <- data.frame(cluster, centers_1)

# Reshape the data
center_reshape <- gather(center_df, features, values, player_age:offspeed_range_speed)
head(center_reshape)

g_heat_4 <- ggplot(data = center_reshape, aes(x = features, y = cluster, fill = values)) +
  scale_y_continuous(breaks = seq(1, 4, by = 1)) +
  geom_tile() +
  coord_equal() + 
  theme_set(theme_bw(base_size = 22) ) +
  scale_fill_gradient2(low = "blue", # Choose low color
                       mid = "white", # Choose mid color
                       high = "red", # Choose high color
                       midpoint =0, # Choose mid point
                       space = "Lab", 
                       na.value ="grey", # Choose NA value
                       guide = "colourbar", # Set color bar
                       aesthetics = "fill") + # Select aesthetics to apply
  coord_flip()
g_heat_4
```

```{r}
# K Means Clustering 2020

set.seed(12345) # Set seed for reproducibility
fit_14 <- kmeans(x = scale_pitchers_2020[4:139], # Set data as explantory variables 
                centers = 4,  # Set number of clusters
                nstart = 25, # Set number of starts
                iter.max = 100 ) # Set maximum number of iterations to use

# Extract clusters
clusters_1 <- fit_14$cluster
# Extract centers
centers_1 <- fit_14$centers

summary(as.factor(clusters_1))

scale_pitchers_2020$last_name[clusters_1 == 1] # look into this cluster
scale_pitchers_2020$last_name[clusters_1 == 2]
scale_pitchers_2020$last_name[clusters_1 == 3]
scale_pitchers_2020$last_name[clusters_1 == 4]

cluster <- c(1: 4)
center_df <- data.frame(cluster, centers_1)

# Reshape the data
center_reshape <- gather(center_df, features, values, player_age:offspeed_range_speed)
head(center_reshape)

g_heat_5 <- ggplot(data = center_reshape, aes(x = features, y = cluster, fill = values)) +
  scale_y_continuous(breaks = seq(1, 4, by = 1)) +
  geom_tile() +
  coord_equal() + 
  theme_set(theme_bw(base_size = 22) ) +
  scale_fill_gradient2(low = "blue", # Choose low color
                       mid = "white", # Choose mid color
                       high = "red", # Choose high color
                       midpoint =0, # Choose mid point
                       space = "Lab", 
                       na.value ="grey", # Choose NA value
                       guide = "colourbar", # Set color bar
                       aesthetics = "fill") + # Select aesthetics to apply
  coord_flip()
g_heat_5
```

```{r}
# Bootstrap Aggregation (Bagging)

library(randomForest)
library(rpart)
library(caret)
library(Metrics)
```

```{r}
# Create training and test data
set.seed(258506) # Set random number generator seed for reproducability
test_ind <- sample(1:139, 139 * 0.2, replace = FALSE) # Select test samples

updated_pitchers_no_name <- updated_pitchers[, c(4:5, 7:139)]
imputed_pitchers <- rfImpute(x = updated_pitchers_no_name, y = updated_pitchers$p_win, iter=5, ntree=300)

train_data <- imputed_pitchers[-test_ind, -1] # Create training data
test_data <- imputed_pitchers[test_ind, -1] # Create test data
```

```{r}
# Run Bagging Model

set.seed(258506) # Set random number generator seed for reproducability
# Use random forest to do bagging
bag_mod <- randomForest(p_win ~., # Set tree formula
                data = train_data, # Set dataset
                mtry = 134, # Set mtry to number of variables 
                ntree = 300) # Set number of trees to use
bag_mod # View model
```

```{r}
# Plot Bagging Model and compare results

bag_preds <- predict(bag_mod, test_data) # Create predictions for bagging model

plot_data <- cbind.data.frame(bag_preds, test_data$p_win)
names(plot_data) <- c("predictions", "actual")
g_22 <- ggplot(plot_data, # Set dataset
              aes(x = predictions,  # Set predictions
                  y = actual)) +  # Set actual
  geom_point(alpha = 0.7) + # Set geom_point for scatter
  geom_smooth() + # Show regression line
  dark_theme_bw() + # Set theme as dark mode
   theme(legend.position = "right", # Turn off legend
     panel.grid.major = element_blank(), # Remove grid
        panel.grid.minor = element_blank(), # Remove grid
        panel.border = element_blank(), # Remove grid
        panel.background = element_blank()) +  # Remove grid
    labs(y= "Actual Wins", x ="Predicted Wins", # Set labels
       title = "Predicted vs. Actual Win Correlation (Bagging)",
       subtitle = "MLB Pitchers 2016-2020")
g_22

rmse(test_data$p_win, bag_preds)
```

```{r}
# Assess Bagging performance with MSE

mse_error <- bag_mod$mse # Extract mean squared error
plot_dat <- cbind.data.frame(rep(1:length(mse_error)), mse_error) # Create plot data
names(plot_dat) <- c("trees", "mse_error") # Name plot data

# Plot Mean Squared Error
g_23 <- ggplot(plot_dat, aes(x = trees, y = mse_error)) + # Set x as trees and y as error
  geom_point(alpha = 0.5, color = "blue") + # Select geom point
  theme_bw() + # Set theme
  theme(panel.grid.major = element_blank(), # Remove grid
        panel.grid.minor = element_blank(), # Remove grid
        panel.border = element_blank(), # Remove grid
        panel.background = element_blank()) + # Remove grid 
  labs(x = "Number of Trees", title = "Mean Squared Error v Number of Trees",
       y = "Mean Squared Error")  # Set labels
g_23 # Print plot
```

```{r}
# Bagging with Variable Importance

bag_mod_2 <- randomForest(p_win ~., # Set tree formula
                data = train_data, # Set dataset
                mtry = 134, # Set number of variables to try  
                ntree = 300, # Set number of trees
                nodesize = 200,  # Set node size
                importance = TRUE, # Set to true to generate importance matrix
                proximity = TRUE) # Set to true to generate proximity matrix
                
# Extract Importance
importance_matrix <- importance(bag_mod_2)
# Print importance matrix
importance_matrix

varImpPlot(bag_mod_2, type = 2, n.var = 10) # Plot importance
```


```{r}
# XGBoost

library(xgboost)
library(caret)
library(OptimalCutpoints)
library(ggplot2)
library(xgboostExplainer)
library(pROC)
```

```{r}
# Create training matrix
dtrain <- xgb.DMatrix(data = as.matrix(train_data[, c(1, 3:135)]), label = train_data$p_win)
# Create test matrix
dtest <- xgb.DMatrix(data = as.matrix(test_data[, c(1, 3:135)]), label = test_data$p_win)
```

```{r}
# Run XGBoost Model

set.seed(234567)
bst_1 <- xgboost(data = dtrain, # Set training data
               
               nrounds = 100, # Set number of rounds
               
               verbose = 1, # 1 - Prints out fit
                print_every_n = 20) # Prints out result every 20th iteration
```

```{r}
# Plot XGBoost Model and compare results

boost_preds <- predict(bst_1, dtest) # Create predictions for xgboost model

pred_dat <- cbind.data.frame(boost_preds , test_data$p_win)#
names(pred_dat) <- c("predictions", "response")

g_24 <- ggplot(pred_dat, # Set dataset
              aes(x = predictions,  # Set predictions
                  y = response)) +  # Set response
  geom_point(alpha = 0.7) + # Set geom_point for scatter
  geom_smooth() + # Show regression line
  dark_theme_bw() + # Set theme as dark mode
   theme(legend.position = "right", # Turn off legend
     panel.grid.major = element_blank(), # Remove grid
        panel.grid.minor = element_blank(), # Remove grid
        panel.border = element_blank(), # Remove grid
        panel.background = element_blank()) +  # Remove grid
    labs(y= "Response Wins", x ="Predicted Wins", # Set labels
       title = "Predicted vs. Response Win Correlation (XGBoost)",
       subtitle = "MLB Pitchers 2016-2020")
g_24

rmse(test_data$p_win, boost_preds)

```

```{r}
# Extract importance
imp_mat <- xgb.importance(model = bst_1)
# Plot importance (top 10 variables)
xgb.plot.importance(imp_mat, top_n = 10)
```

```{r}
source("a_insights_shap_functions.r")

# Calculate SHAP importance
shap_result <- shap.score.rank(xgb_model = bst_1, 
                X_train =as.matrix(train_data[, c(1, 3:135)]),
                shap_approx = F)
# Plot SHAP importance
var_importance(shap_result, top_n=10)
shap_long = shap.prep(shap = shap_result,
                           X_train = as.matrix(train_data[, c(1, 3:135)]), 
                           top_n = 10)


plot.shap.summary(data_long = shap_long)
```

```{r}
library(dplyr)
# rownames(scale_pitchers_2017)
# rownames(scale_pitchers_2018)
# rownames(scale_pitchers_2019)
# rownames(scale_pitchers_2020)

# Subset Players Analysis

elite_pitchers_2017 <- pitchers_2017[rownames(scale_pitchers_2017) %in%
                                       c(" Max Scherzer"," Chris Sale"," Zack Greinke"," Jacob deGrom",
                                         " Justin Verlander"," Yu Darvish"," Stephen Strasburg",
                                         " Carlos Carrasco"," Ervin Santana"," Corey Kluber",
                                         " Luis Severino"," Robbie Ray"," Clayton Kershaw"," Chris Archer",
                                         " Gerrit Cole","Jimmy Nelson"),
                                     colnames(scale_pitchers_2017) %in%
                                       c("last_name","first_name","groundballs","fs_avg_spin","out_zone",
                                         "n","edge","out_zone_swing","linedrives","woba","pitch_count",
                                         "in_zone_swing")]
elite_pitchers_2018 <- pitchers_2018[rownames(scale_pitchers_2018) %in%
                                       c(" Zack Wheeler"," Charlie Morton"," Miles Mikolas"," Sonny Gray",
                                         " Jameson Taillon"," Blake Snell"," Luis Severino",
                                         " Nick Pivetta"," German Marquez"," Justin Verlander",
                                         " Gerrit Cole"," Trevor Bauer"," Jacob deGrom"," Aaron Nola",
                                         " Mike Clevinger"," Max Scherzer"," Mike Foltynewicz",
                                         " Carlos Carrasco"," Jose Berrios"," Corey Kluber"),
                                     colnames(scale_pitchers_2017) %in%
                                       c("last_name","first_name","groundballs","fs_avg_spin","out_zone",
                                         "n","edge","out_zone_swing","linedrives","woba","pitch_count",
                                         "in_zone_swing")]
elite_pitchers_2019 <- pitchers_2019[rownames(scale_pitchers_2019) %in%
                                       c(" Marcus Stroman"," Charlie Morton"," Sonny Gray",
                                         " Luis Castillo"," Adam Wainwright"," Aaron Nola"," Mike Soroka",
                                         " Zack Greinke"," Stephen Strasburg"," Yu Darvish",
                                         " Trevor Bauer"," Matthew Boyd"," Max Scherzer"," Walker Buehler",
                                         " Zack Wheeler"," Lucas Giolito"," Gerrit Cole"," Jacob deGrom",
                                         " Mike Minor"," Clayton Kershaw"," Justin Verlander",
                                         " Noah Syndergaard"," Lance Lynn"," Jack Flaherty"),
                                     colnames(scale_pitchers_2017) %in%
                                       c("last_name","first_name","groundballs","fs_avg_spin","out_zone",
                                         "n","edge","out_zone_swing","linedrives","woba","pitch_count",
                                         "in_zone_swing")]
elite_pitchers_2020 <- pitchers_2020[rownames(scale_pitchers_2020) %in%
                                       c(" Kenta Maeda"," Dylan Bundy"," Dinelson Lamet"," Lance Lynn",
                                         " Gerrit Cole"," Carlos Carrasco"," Yu Darvish"," Shane Bieber",
                                         " Trevor Bauer"," Jacob deGrom"," Brandon Woodruff",
                                         " Lucas Giolito"),
                                     colnames(scale_pitchers_2017) %in%
                                       c("last_name","first_name","groundballs","fs_avg_spin","out_zone",
                                         "n","edge","out_zone_swing","linedrives","woba","pitch_count",
                                         "in_zone_swing")]
elite_pitchers_2017
elite_pitchers_2018
elite_pitchers_2019
elite_pitchers_2020
``` 

```{r}
summary(elite_pitchers_2017)
summary(elite_pitchers_2018)
summary(elite_pitchers_2019)
summary(elite_pitchers_2020)
```

```{r}
# Rest of League
'%ni%' <- Negate('%in%')

non_elite_pitchers_2017 <- pitchers_2017[rownames(scale_pitchers_2017) %ni%
                                       c(" Max Scherzer"," Chris Sale"," Zack Greinke"," Jacob deGrom",
                                         " Justin Verlander"," Yu Darvish"," Stephen Strasburg",
                                         " Carlos Carrasco"," Ervin Santana"," Corey Kluber",
                                         " Luis Severino"," Robbie Ray"," Clayton Kershaw"," Chris Archer",
                                         " Gerrit Cole","Jimmy Nelson"),
                                     colnames(scale_pitchers_2017) %in%
                                       c("last_name","first_name","groundballs","fs_avg_spin","out_zone",
                                         "n","edge","out_zone_swing","linedrives","woba","pitch_count",
                                         "in_zone_swing")]
non_elite_pitchers_2018 <- pitchers_2018[rownames(scale_pitchers_2018) %ni%
                                       c(" Zack Wheeler"," Charlie Morton"," Miles Mikolas"," Sonny Gray",
                                         " Jameson Taillon"," Blake Snell"," Luis Severino",
                                         " Nick Pivetta"," German Marquez"," Justin Verlander",
                                         " Gerrit Cole"," Trevor Bauer"," Jacob deGrom"," Aaron Nola",
                                         " Mike Clevinger"," Max Scherzer"," Mike Foltynewicz",
                                         " Carlos Carrasco"," Jose Berrios"," Corey Kluber"),
                                     colnames(scale_pitchers_2017) %in%
                                       c("last_name","first_name","groundballs","fs_avg_spin","out_zone",
                                         "n","edge","out_zone_swing","linedrives","woba","pitch_count",
                                         "in_zone_swing")]
non_elite_pitchers_2019 <- pitchers_2019[rownames(scale_pitchers_2019) %ni%
                                       c(" Marcus Stroman"," Charlie Morton"," Sonny Gray",
                                         " Luis Castillo"," Adam Wainwright"," Aaron Nola"," Mike Soroka",
                                         " Zack Greinke"," Stephen Strasburg"," Yu Darvish",
                                         " Trevor Bauer"," Matthew Boyd"," Max Scherzer"," Walker Buehler",
                                         " Zack Wheeler"," Lucas Giolito"," Gerrit Cole"," Jacob deGrom",
                                         " Mike Minor"," Clayton Kershaw"," Justin Verlander",
                                         " Noah Syndergaard"," Lance Lynn"," Jack Flaherty"),
                                     colnames(scale_pitchers_2017) %in%
                                       c("last_name","first_name","groundballs","fs_avg_spin","out_zone",
                                         "n","edge","out_zone_swing","linedrives","woba","pitch_count",
                                         "in_zone_swing")]
non_elite_pitchers_2020 <- pitchers_2020[rownames(scale_pitchers_2020) %ni%
                                       c(" Kenta Maeda"," Dylan Bundy"," Dinelson Lamet"," Lance Lynn",
                                         " Gerrit Cole"," Carlos Carrasco"," Yu Darvish"," Shane Bieber",
                                         " Trevor Bauer"," Jacob deGrom"," Brandon Woodruff",
                                         " Lucas Giolito"),
                                     colnames(scale_pitchers_2017) %in%
                                       c("last_name","first_name","groundballs","fs_avg_spin","out_zone",
                                         "n","edge","out_zone_swing","linedrives","woba","pitch_count",
                                         "in_zone_swing")]
non_elite_pitchers_2017
non_elite_pitchers_2018
non_elite_pitchers_2019
non_elite_pitchers_2020
```

```{r}
summary(non_elite_pitchers_2017)
summary(non_elite_pitchers_2018)
summary(non_elite_pitchers_2019)
summary(non_elite_pitchers_2020)
```

```{r}
print("2017 Groundballs")
mean(elite_pitchers_2017$groundballs)
mean(non_elite_pitchers_2017$groundballs)
print("2018 Groundballs")
mean(elite_pitchers_2018$groundballs)
mean(non_elite_pitchers_2018$groundballs)
print("2019 Groundballs")
mean(elite_pitchers_2019$groundballs)
mean(non_elite_pitchers_2019$groundballs)
print("2020 Groundballs")
mean(elite_pitchers_2020$groundballs)
mean(non_elite_pitchers_2020$groundballs)
```

Interesting how elite pitchers averaged slightly lower amounts of groundballs compared to the rest of the league. 


